### ISSUE TITLE
Illegal request.

### ISSUE THREAD

**Issue by JmCourir** [tinuzz/wp-plugin-trackserver#1]
Hi! 

I get Illegal request.   on wordpress website. 

Any clue?

Thanks,

**Comment by tinuzz** [comment]
Can you give me some more information?
- What is the actual request?
- What does your Trackserver configuration look like?

Thank you.

**Comment by JmCourir** [comment]
Hi, 

I installed the plugin Trackserver to my latest Wordpress version. Installed successfully. Than I configured OruxMaps to my server. Than I entered the login and password of MapMyTrack which was wrong... Of course it says username or password is incorrect.  So than I did entered the good login and password of my Wordpress admin.   When it asking me again the login password, I enter the Wordpress login and when I clic on ok, I get a white page saying Illegal Request.  This was with Chrome.  Than I tested it with Internet Explorer and I get another message, HTTP 501/HTTP 505 Not implimented.... 

With Internet Explorer
![2015-07-21062122](https://cloud.githubusercontent.com/assets/4047435/8798512/c626f668-2f70-11e5-9802-32e9c9dd2e54.png)

With Chrome
![2015-07-21062234](https://cloud.githubusercontent.com/assets/4047435/8798534/f94a01e8-2f70-11e5-8026-a8f53b406e3c.png)


Thanks for the reply :)

**Comment by tinuzz** [comment]
Yes, the "Illegal request" response is because you open the MapMyTracks slug ('maps') in the browser. You're not supposed to do that. That URL (meaning: the slug that you configured in Trackserver for the MapMyTracks protocol) is meant for OruxMaps to send location updates to, it is not meant to do anything when you open it in a browser. The request is not a valid MapMyTracks protocol update, so it is in fact illegal in this context.

Best regards,
Martijn.

**Comment by JmCourir** [comment]
Hi, thanks for replying so fast. 

Hhhmm.... where can I see on the web the live tracking map of uploaded tracks?  

Is there any? 

Again, thanks for helping me, little bit confused here... 

Micboule

**Comment by tinuzz** [comment]
Hi,

I realize now that the documentation is lacking a little, but the use of the plugin is described on the 'Installation' tab of the plugin information, that you can also view via 'View details' on the plugins page of your Wordpress admin backend.

https://wordpress.org/plugins/trackserver/installation/

5. Use the shortcode [tsmap] to include maps and tracks in your posts and pages.

Then look at the FAQ page

https://wordpress.org/plugins/trackserver/faq/

for all the attributes the shortcode supports.

I should improve the documentation.

Best regards,
Martijn,

**Comment by JmCourir** [comment]
Thank you again Tinuzz I really appreciate it.
