### ISSUE TITLE
[Wish] Geofencing

### ISSUE THREAD

**Issue by wrohdewald** [tinuzz/wp-plugin-trackserver#10]
Use case: I do not want my home address to be deductible from public tracks.

Defining one fence would be enough (for me), and rectangular or circular would both be fine. 

I personally would be happy to have just one fence, and manually entering values would be just fine for me.

**Comment by tinuzz** [comment]
Just a quick update: a new version of Trackserver will be released soon(ish) and it will have geofencing support.

**Comment by tinuzz** [comment]
Trackserver v4.0 was just released with geofencing support.

**Comment by wrohdewald** [comment]
Can you please add some way to apply geofencing to existing tracks? Right now it seems I have to download a track and re-upload it to get things applied (which I did not actually try). That is a problem if somebody wants to change fences and she has hundreds of existing tracks.

The "Recalculate" action in the track manager seems like a good place to add this. And mention this in the help text for the fences in the profile.


And - if there are fences which actually discard locations, ask the user for confirmation before re-applying the fencing.

A small thing in the list of fences:
1. create 3 fences
2. remove the 2nd one
3. now the empty row for creating a new fence is in the middle of the list. I think the empty row should always be the last one.

**Comment by tinuzz** [comment]
Yes, your first suggestion was actually on my TODO list, but I really wanted to get 4.0 out there. Reapplying fences is not very hard to implement, so expect that in 4.1.

About the sort order of the list... This might also be doable :-)
