### ISSUE TITLE
hi guys,

### ISSUE THREAD

**Issue by artboxromania** [tinuzz/wp-plugin-trackserver#11]
i have a small problem with trackserver.  I am using osmand gps tracker and the frontend map from de website not showing the lat and long, speed and other things.  Another issue is that i want to change the leaflet map. On osmand i am using hike and bike map. Can i put the same map on the wordpress frontend map? Thank you

**Comment by tinuzz** [comment]
Hi,

"not showing the lat and long, speed and other things" is not really enough information. Can you describe what you are trying to do, what your shortcode looks like and what exactly doesn't work? URLs where I can check help too.

You can change the map tile server URL in Trackserver settings. You'll have to find out the tile server URL for the hike and bike map yourself.

Best regards,
Martijn.

**Comment by tinuzz** [comment]
It has beeen two months. I'm closing this issue.
