### ISSUE TITLE
[Feature Request] Alternative maps

### ISSUE THREAD

**Issue by edes** [tinuzz/wp-plugin-trackserver#13]
Hey Martijn
I'm sure the outdoor guys (like myself) among the Trackserver users would love to see  i.e. opencyclemap, maps with hillshading,... as alternative basemaps instead of the plain openstreetmap. Any chance to see that in future?
Best, Hannes

**Comment by tinuzz** [comment]
Hello Hannes,

It has been possible to specify your own tile server URL in Trackserver settings. Doesn't that do what you need?

Best regards,
Martijn.

**Comment by edes** [comment]
Yes, that's exactly what I needed - just didn't realize how it's done properly. Thanks for your immediate answer (and for the whole plugin - loving it!).

**Comment by edes** [comment]
In future versions it would be great to have an option to define multiple tile servers and let the visitor switch between base maps. For example it usually doesn't make sense to use satellite images as global base map, but they can be very useful when it comes to exploring details at higher zoom levels.
Best, Hannes

**Comment by tinuzz** [comment]
I have been thinking about implementing something like "map profiles" to make switching between map styles easier, but I haven't really decided on how it should be done.

If you like Trackserver, would you consider writing a review on Wordpress.org? https://wordpress.org/plugins/trackserver/#reviews

Btw, a new release is coming soon(ish ;-)).
