### ISSUE TITLE
Data is empty

### ISSUE THREAD

**Issue by JmCourir** [tinuzz/wp-plugin-trackserver#2]
Hi, 

It's me again... 

 Using OruxMaps... 

It seems to communicate with Wordpress plugin but there is no data inside of the log. I did upload manually a GPX file from OruxMaps and it does put data "Points and Distance" in the log. 

Thanks again for your help :+1:

**Comment by tinuzz** [comment]
How long did you have OruxMaps running with live tracking enabled? OruxMaps generally needs a few minutes before the first data points are uploaded.

**Comment by JmCourir** [comment]
Here is a screenshot of Data....

I've done a cycling workout yesterday and no data was uploaded. 

![20150721085403](https://cloud.githubusercontent.com/assets/4047435/8801246/25c6427a-2f87-11e5-8ac8-f9b5625a634e.png)

**Comment by JmCourir** [comment]
Any other info you need?

**Comment by tinuzz** [comment]
Hi,

I cannot explain this. It appears that a 'start_activity' request is working correctly, while a 'update_activity' is not. This cannot be caused by some misconfiguration, so you may have a bug here. In my setup, OruxMaps 6.0.9 is working fine.

Can you tell me:
- Do you have the latest version of the plugin, 1.7?
- Your WordPress version
- The PHP version WP is running on

Thanks,
Martijn.

**Comment by tinuzz** [comment]
One more thing.. can you check you PHP error log for errors in trackserver.php?

**Comment by JmCourir** [comment]
Hi, 
I have 4.2.2 Wordpress
Version 1.7 Trackserver
PHP 5.2.17   -   I've tried to put the server with version 5.3 like you recommend but doesn't seems to apply it. I use CPanel. 

It may be the problem finally.... :/

**Comment by JmCourir** [comment]
ok, will give you this log right away

**Comment by tinuzz** [comment]
Maybe I wasn't clear with this, but PHP 5.3 is not a recommendation, it is an absolute requirement. Trackserver does NOT WORK with PHP < 5.3.

Don't bother with the PHP error log, I already know what it will say.
