### ISSUE TITLE
No Connection from OwnTracks

### ISSUE THREAD

**Issue by m-art-in** [tinuzz/wp-plugin-trackserver#25]
Hi,
I'm running the app OwnTracks 2.1.2 and the Trackserver 4.3. - Both should be the newest version, but unfortunately my mobile device can't connect the wordpress page. 

I configured OwnTrack:
- http-mode: TRUE
- host: as given as on the trackserver plugin-page
- Identification: USERNAME same as the wordpress user (Administrator), PASSWORD: wordpress password, DEVICE-ID and TRACKER-ID are both empty.

I set debugInfo in the OwnTracks-APP to TRUE, but the info is only short:
When I try to submit a valid GPS position in the logfile there is only the message:

`endpointUserInfo:null
CA: sideload: false, using system keystore`

Unfortunately I can't give you any further error details - there are none.

Thanks for tips and help!

**Comment by tinuzz** [comment]
Hi,

The 'CA: sideload: false' message is just an informational message, if I read the OwnTracks source correctly.

What makes you reach the conclusion that OwnTracks cannot connect to WordPress?
Can you post the URL, so I can have a look?

Best regards,
Martijn.

**Comment by m-art-in** [comment]
Hi Martijn,

> What makes you reach the conclusion that OwnTracks cannot connect to WordPress?
because I have a valid position with OwnTracks but it's not saved on the WordPress Side. With the TrackMe App it's fine.

> Can you post the URL, so I can have a look?
Yes: http://wp.martingruner.de/index.php/owntracks/

Thanks

**Comment by tinuzz** [comment]
Alright, no HTTPS, so certificate issues are ruled out. This is something you should fix ;-)

Anything logged in your webserver's access- or error log?

Cheers,
Martijn.

**Comment by m-art-in** [comment]
No errors there, either... 
I tried with OruxMaps, too: But also no success. Only TrackMe saves the geodata correctly. If you would have an idea this would be great, but if not I'm fine with TrackMe, too.

**Comment by tinuzz** [comment]
No errors in the log, but can you find the requests from Owntracks in the access log?

You have to do some troubleshooting yourself. For me, both OruxMaps and Owntracks work correctly. Not always 100% reliable, but at least basic tracking works.

I cannot look in your access logs and you have told me _nothing_ about your setup, not even which webserver you run.

**Comment by m-art-in** [comment]
The webserver is a commercial provider (webhoster). Therefore I have hardly influence on the installation and configuration. Debugging is therefore almost impossible. I stay with TrackMe and that's fine.
