### ISSUE TITLE
http request with Arduino

### ISSUE THREAD

**Issue by albertomercurio** [tinuzz/wp-plugin-trackserver#27]
I want to sent my Arduino location with http request. The problem is that i don't know the http GET or POST method fot upload my data. I saw that there is an http request, but i don't know the syntax.

**Comment by tinuzz** [comment]
Easiest way is the OsmAnd protocol. All the URL parameters can be found as 'Full URL' in the Trackserver profile.

**Comment by albertomercurio** [comment]
Ok thank you it worked! Another question: is there a way to get the last 50 track? I know that the track syntax is "track=34,35,36,37" for example. I think something like "track=-50:" but of course it didn't work.

**Comment by tinuzz** [comment]
Sorry, Trackserver doesn't currently support getting ranges of tracks in any way. It has been on the roadmap for a while, but I never got around to implementing it.

Can you open a separate Github ticket and create a wishlist request?
