### ISSUE TITLE
Data is empty... even after updating PHP version

### ISSUE THREAD

**Issue by JmCourir** [tinuzz/wp-plugin-trackserver#3]
Hi, 
Ok after looking more deeply to see what version I have, I did upgrade to version 5.4 of PHP. It still not getting the activity. 

My version of PHP: PHP Version 5.4.43

Here is what is activated:
![2015-07-22071346](https://cloud.githubusercontent.com/assets/4047435/8824207/bb249faa-3041-11e5-911a-f6d95a2495d2.png)

I've been trying with Galaxy Note 3 and Galaxy Note 8 Android - no luck. 

Looks like it's something in my web server... 

![2015-07-22072254](https://cloud.githubusercontent.com/assets/4047435/8824320/866a1384-3042-11e5-8e35-e46325d5f6a1.png)

OruxMap version I also tried: 
Beta: V 6.5.0rc2 & V 6.0.9

I did also delete the plugin and reinstalled.

Woud you suggest to reinstall Wordpress? My Wordpress is currently empty anyway...

**Comment by tinuzz** [comment]
Anything in the PHP error log?

**Comment by JmCourir** [comment]
Hi, 
Let me find that log.... I need to make a search on that log...

**Comment by tinuzz** [comment]
It's location should be specified in php.ini as 'error_log' option. You can also see it in the output of phpinfo();

**Comment by JmCourir** [comment]
Does this link can help you?

http://www.jmcourir.com/phpinfo.php

**Comment by tinuzz** [comment]
I can also try to have a look myself if you're willing to give me an account on your blog with at least author rights. My e-mail is m@rtijn.net.

**Comment by tinuzz** [comment]
Your phpinfo() output is not really helpful. The error_log is specified as a relative file name and I have no idea what the location is resolved to in the context of a FastCGI server.

**Comment by JmCourir** [comment]
Just to make sure... You would like to have access to the Wordpress ? That's ok for me.

**Comment by tinuzz** [comment]
Yes, with a WordPress account I can at least test Trackserver from here and MAYBE see what's wrong.

**Comment by JmCourir** [comment]
Done, you should have receive a email

**Comment by JmCourir** [comment]
Tell me if you got access...

**Comment by tinuzz** [comment]
Hi,

I have no idea what is wrong with your setup. From what I see: not much.

I first did a test from my own computer with 'wget', I was able to add a track and to add a location point to it after that. See track ID 17 in your database.

Then I configured OruxMaps on my phone for your website and started a track log. Within a few minutes, I had a track with 119 locations in Trackserver. See track ID 18 in your database.

Everything appears to be working as it should....

**Comment by JmCourir** [comment]
Hmm, Kind of weird, I dont see further than ID 16 in Manage Tracks.... is it because I'm not logged with your username into Wordpress?

**Comment by JmCourir** [comment]
Ok, yep, I got to log into your username to find ID 17 and 18

**Comment by JmCourir** [comment]
I'll put your username and password into OruxMaps to see how it goes...

**Comment by JmCourir** [comment]
Ok, after testing with your username and password, I still get no points and Data :(    So weird...

**Comment by tinuzz** [comment]
And you have

http://www.jmcourir.com/map

as the custom URL in OruxMaps?

**Comment by JmCourir** [comment]
![screenshot_2015-07-22-10-10-00](https://cloud.githubusercontent.com/assets/4047435/8827301/ed8e8484-3059-11e5-943f-79bef207315c.png)

**Comment by tinuzz** [comment]
Maybe it's a a language issue, although I can't image how that could be the problem. I'll try to investigate later, but that will probably be next week.

Maybe in the mean time you can try switching OruxMaps to English and see if that works?

**Comment by JmCourir** [comment]
Sure, I can do that right away! 
Thanks for the help

**Comment by JmCourir** [comment]
Language: English --- no change unfortunatly

**Comment by JmCourir** [comment]
Could it be the units side? 
![screenshot_2015-07-22-10-34-43](https://cloud.githubusercontent.com/assets/4047435/8827905/5b05a1e8-305d-11e5-82c8-f9c7a571687d.png)

**Comment by tinuzz** [comment]
Hm, that looks exactly the same as in my OruxMaps settings, but I feel it MUST be something like this.

To be able to really check this, I am going to ask you to use MY WordPress install for testing, so I can see exactly what your OruxMaps is sending. I will have to create a user account for you. However, I won't be able to do that before Tuesday next week due to a short vacation.

**Comment by JmCourir** [comment]
Ok, I found something that got my attention. I have uninstalled OruxMaps and re-installed it, than I got a popup of what apps was using GPS location in my device. OruxMaps wasn't in the list... let me put you a screenshot of it.

**Comment by JmCourir** [comment]
Trying to get that popup again.... meanwhile I was thinking, I have another tablet at home which is doing the same thing, giving a log withouth activity... maybe it's not a Android OS related...

**Comment by tinuzz** [comment]
Well, I'm not going to speculate anymore ;-) Let's see what exactly OruxMaps is doing wrong next week.

**Comment by JmCourir** [comment]
Ok Martin, no problem, OruxMaps have the authorization to send data with GPS enabled. So it's not a question of authorization. I'll do more test on my side. It's ok if you dont answer, I know that your have also a life :)     I already appreciate your help, very kind of you Martin.

**Comment by JmCourir** [comment]
Another question for you, does Data Points and Distance is supposed to increase by itself or you need to upload it manually?  Maybe I dont understand the function of your plugin...  ? I know that I can upload successfully any gpx and it will show points and data like it should be. But the way I understand it, because of "live" possibility, it's uploading data by itself.

**Comment by tinuzz** [comment]
Every time one ore more data points are added, via TrackMe, OruxMaps or OsmAnd live tracking, the distance of the track is recalculated. The number of points is just the actual number of points associated with a track, it is not a calculated number that needs to be refreshed. You can be sure that when 'data points' is 0, the distance is also 0.

What do you think my plugin is supposed to do?

What do you mean by 'uploading data by itself' ?

Cheers,
Martijn.

**Comment by JmCourir** [comment]
Hi Marjin, 
Thanks for replying, ok I understand how it's working, it's like I thought.

So, in live tracking, the OruxMaps will send my position and will update right away on the map with the last position received. 

Should I try it with TrackMe to see if it's gonna work? 

Have a nice day,

**Comment by tinuzz** [comment]
Hi,

Can you send me a private email on m@rtijn.net? I'd like you to test something for me, using my server and I'd like to send you the necessary credentials.

Regards,
Martijn.

**Comment by tinuzz** [comment]
Hi M,

Did you receive my mail?

Regards,
Martijn.

**Comment by JmCourir** [comment]
Hi Martjin, 

Yes I have receive, I'll do the test during the day today. Sorry, I've been really sick yesterday. 

Thanks for checking... 

Michel,

**Comment by JmCourir** [comment]
Hi, 

I just did the test for you. 

Let me know...

**Comment by tinuzz** [comment]
I don't see anything that resembles a request from OruxMaps. Can you try again?

**Comment by JmCourir** [comment]
Hi, 

Ok making the test right away.... I did it with OruxMaps and than I went to your website trying logging in if it was working.... 

Going to make back the test with OruxMaps.

**Comment by JmCourir** [comment]
It's now "ON" live tracking with OruxMaps

**Comment by JmCourir** [comment]
I just stopped the live tracking....

**Comment by JmCourir** [comment]
Will rewrite the password in case of an error

**Comment by JmCourir** [comment]
Hi Martijn, 

Now that the problem is solved, can I say you any recommendations? 

Would it be possible to get more information on the map of (ex: Current Speed, Heart Rate, Altitude, etc....) I'm just asking... 

Have a nice day! 
Michel,

**Comment by tinuzz** [comment]
An issue with the parsing of coordinates in the MapMyTracks protocol handler was causing this problem. It was fixed in version 1.8, released today.
