### ISSUE TITLE
GPX UPLOAD NOT VALIDATED

### ISSUE THREAD

**Issue by mariobarretta** [tinuzz/wp-plugin-trackserver#33]
I've uploaded the gpx file created with trackme but on trackserver plugin for wordpress i receive ERROR: File ‘Test .gpx’ could not be validated as GPX 1.1 and i can not proceed to show map  for live position on site.

**Comment by tinuzz** [comment]
Hi,

I am sorry for not responding to this issue. The error you get is a strong indication that the file is not valid GPX 1.1. If it's not valid GPX, Trackserver cannot read it.

Best regards,
Martijn.
