### ISSUE TITLE
slug /trackme leads to 404

### ISSUE THREAD

**Issue by drJeckyll** [tinuzz/wp-plugin-trackserver#35]
I may miss something simple here, but on my clean install of wordpress from docker container with plugin installed and trackme on my phone I get error 404.

```
trackserver  | 172.16.23.1 - - [18/Jun/2022:18:10:00 +0000] "GET /trackme/[username]/[password]/cloud.z?a=update&dn=[username]&id=7b78adba1d21521c&lat=[lat]&long=[long]&do=2022-06-18%2021:10:00&pub=1&db=8&acc=18.977&ang=0.0&sp=0.0&alt=200.29998779296875 HTTP/1.1" 404 61818 "-" "-"
```

I'm running wordpress behind reverse https proxy (traefik). Also my username contain capital letter if that make any difference. Password is correct. I didn't touch slug in plugin config.

So is there any changes which I have to make in wordpress/plugin which I miss?

**Comment by drJeckyll** [comment]
Using code from github seems to work.
Install from plugins UI in wordpress seems to have old version which don't work even it looks like same version 4.3.2.

**Comment by tinuzz** [comment]
Hi,

Just for the record: I'm not sure why you would get a 404, if the URL you configured in TrackMe is the URL that Trackserver displayed, but I haven't had any other complaints about this.  The version on wordpress.org hasn't been updated for a long time, and it it possible that advances in WordPress itself introduced an error. I must admit that I don't regularly test the published version on new releases of WordPress.

The code on Github is ahead by 160 commits, compared to the latest official release. In fact, I have been working towards a 5.0 release for a long time, but I'm not 100% there. In any case, the current code in 'master' is not the same as v4.3.2, even though the code still say so. I'm sorry about that, I'll update the version in Github to something more representative.

Best regards,
Martijn.

**Comment by tinuzz** [comment]
I forgot to say, I _do_ appreciate and encourage people to download the plugin from Github, test it and report any issues. I always run the latest code on the latest version of WP myself, but I cannot test it in all the different hosting environments that people cook up ;-)

**Comment by drJeckyll** [comment]
I don't have idea either, but I just uninstall plugin from wordpress repo and put in place code from github. Settings were retained and I didn't touch them. It just start working, so everything is OK now.
