### ISSUE TITLE
Nothing on map

### ISSUE THREAD

**Issue by Bebarr** [tinuzz/wp-plugin-trackserver#39]
I'm using GPSLogger to send coordinate to trackserver. 
I entered the url into the app and setup as your screenshots. The certificate is ok.
When the app is recording, it send the coordinate. I see it thanks to the "manage tracks" screen. But when I go to the "embedded maps" there is nothing. It says "no tracks to display"

Thanks

**Comment by tinuzz** [comment]
I'm not sure what you're trying to do with embedded maps. To clarify: "embedded maps" are a type of WordPress post, that is rendered full screen. That is the only thing that is special about them: you have to create them like any other post or page, and you have to give them content, which would normally be just a [tsmap] shortcode.

The quickest way to see your track on a map is to create a regular WordPress post (do this as the user that owns the tracks) and enter '[tsmap user=@]' as the content. This should render a map with your latest track on it.

Regards,
Martijn.

**Comment by Bebarr** [comment]
Thanks a lot to clarify that :)
It's working now, the track is on the map.
Is there a way to actualize the map automatically?

**Comment by tinuzz** [comment]
If you use the 'user=@' or 'user=<id>' selector for the track, it will be rendered as a 'live track', which means the map will automatically update every 10 seconds. You should see a 'stop' / 'play' button on the left side of the map.

**Comment by Bebarr** [comment]
Alright thanks you! I wrote the code `tsmap id=<id>`
Now it's working perfectly thanks to you
I hope that you don't waste your time because of me.

**Comment by tinuzz** [comment]
No problem, happy to help ;-) I'm glad you enjoy Trackserver.
