### ISSUE TITLE
I want to change the map, zoom level & want to put my various locations marker as well in the map!

### ISSUE THREAD

**Issue by bondjames12345677** [tinuzz/wp-plugin-trackserver#4]
First of all Thanks to You very much for such an wonderful plugin.

My question is,
is it possible that can I change the map instead of the default map & zoom level & within that map can I put markers for various locations of my own choice?

I will be appreciate if you help me regarding the issue, coz am absolutely clue less!

**Comment by tinuzz** [comment]
Hi,

I'm not quite sure what you are trying to accomplish, but you can change the tile URL for the map in Trackserver's settings. I have no idea what you mean by 'change zoom level'.

If you want to add custom markers to the map, you will have to use JavaScript to do it.

Start by looking at the Javascript source, trackserver.js in particular, and in your browser use Developer Tools or Firebug or something similar to look at the global Trackserver object and its 'mydata' property, that contains a reference to all map-divs and their tracks.

Trackserver.mydata.<mapdiv>.<trackid>.track._map is a direct reference to the L.map object and you should be able to build upon that. If you make sure that Trackserver's JS is loaded first, you can just instantiate L.marker and add it the map.

See http://leafletjs.com/reference.html#marker for more information.

**Comment by tinuzz** [comment]
Since this issue doesn't seem to concern a particular issue with Trackserver, I'm closing it.
