### ISSUE TITLE
Syntax Error - Bad request

### ISSUE THREAD

**Issue by bluefire100** [tinuzz/wp-plugin-trackserver#47]
During traveling in my RV I’m using a Teltonika RUTX50 Router, which gots the ability to send its GPS data in realtime to a website over https. And here comes Trackserver in: I installed the plugin. 
Together with Teltonika support we are trying to bring it to work, but we need to know, which data and in **which format** has to be sent to the configured https address. 

What is the exact syntax? Could you please give a detailed example. We’ve tried countless different syntaxes, but we are either always getting a bad request or a syntax error:

<img width="555" alt="image001" src="https://github.com/user-attachments/assets/419af0a4-a39e-4429-859e-c46c6bb02a1b">

**Comment by tinuzz** [comment]
Hi,

Trackserver supports multiple protocols for location data ingestion.

The simplest one is via HTTP GET, and the parameter format is documented in the Trackserver Profile page, for example under GPSLogger, PhoneTrack or OsmAnd settings. The URL to use, including all the parameters, is listed there. OsmAnd uses the URL that includes authentication data in the URL, which may be the easiest, but you can also use HTTP Basic auth, like this: https://username:password@www...

If you  must use POST requests, you have several different options, like MapMyTracks v1 (https://github.com/MapMyTracks/api-v1) or OwnTracks (https://owntracks.org/booklet/tech/http/).

But I don't really have documentation to support this any further. If you must know exactly how it all works, I recommend that you study Trackserver's source code, right here on Github.

Best regards,
Martijn.
