### ISSUE TITLE
How to dynamically put various location's markers in the map using mysql data!

### ISSUE THREAD

**Issue by bondjames12345677** [tinuzz/wp-plugin-trackserver#5]
First of all Thank You very much for such an wonderful plugin.
Actually its not an issue with the plugins, its a particular query so that, I can use the plugins u made as per my requirement.

My question is,

How to dynamically put various location's markers in the map using mysql data, which containing lat & log info in the data base side!

I tried almost every possible way to achieve it but no luck. I will be great full if you help me regarding this! am absolutely clue less! thanks in advance :)

P.S: By the way for your info that, statically I can able to put my location's markers in the map!

**Comment by tinuzz** [comment]
Hello whatsyourname,

I think you are asking your questions in the wrong place. Please do not open Github issues for things that have nothing to do with this software. I am not a PHP/JavaScript helpdesk, and if you are 'absolutely clueless', as you put it yourself, then you should start by studying the internals of Leaflet and Wordpress. Then, if you have more questions about either subject, there are sites better suited to get help, like StackOverflow. Regarding Trackserver-specific details, I think I have given you enough to start with in issue #4.

Regards,
Martijn.

**Comment by bondjames12345677** [comment]
First of all thank you very much for your Response & am extremely sorry that, I put my question in the wrong place, but as you guide me to find the solution in other place like lifelate & stackoverflow, in this concern I wanna let you know that, I already came across all those sites & their solutions not at all applicable to your pligins, coz all the factor & theirs pros and cons related to your plugins only & that's why again bother you to give us a solution directly & put the question here! May be am in the wrong place to ask my question, but its my belife that you will give us a right solutions! Am extreemly sorry again to bother you! Thank You :)

**Comment by tinuzz** [comment]
Sorry, but you haven't even asked me a proper question yet, so there is nothing I can do for you. Hell, you haven't even told me your name. Please stop wasting my time.

**Comment by bondjames12345677** [comment]
OK no issue, never mind! Any way thanks for your help so far! By the way my
name is James! Thanks again!
