### ISSUE TITLE
No map visible anymore (11 July)

### ISSUE THREAD

**Issue by korpowski** [tinuzz/wp-plugin-trackserver#6]
Hi. In the background apprears now a message, insteand of a map, that "As of July 11, 2016, direct title access has been discontinued" (MapQuest).

Would be great if there would be a fix soon because I'm using your plugin now daily because I'm on a big trip with my motor bike :-)

Thanks
Robert

Update: You can ignore this because I saw a possible solution in in the (plugin) forum

**Comment by tinuzz** [comment]
Hi Robert,

Great, motorbike trips are EXACTLY what Trackserver was made for :-)

Mapbox changed their terms of services. You shoud change the tile server URL in Trackserver's options (scroll down all the way).  Ah, I see that you found my other post about this.

Good luck and have fun!

Cheers,
Martijn.
