### ISSUE TITLE
Load OpenStretmap Tiles with "http|https" 

### ISSUE THREAD

**Issue by fanfarian** [tinuzz/wp-plugin-trackserver#8]
> Mixed Content: The page at '**https://**...' was loaded over HTTPS, but requested an insecure image '**http**://c.tile.openstreetmap.org/...'. This content should also be served over HTTPS.

Possible Fix in trackserver.php Line 81:
`'tile_url' => 'http://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',`

Omit Protocol
`'tile_url' => '//{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',`

**Comment by fanfarian** [comment]
Nevermind, found the settings in the options page.

**Comment by tinuzz** [comment]
Well, removing the scheme from the URL might still be a good idea for the default setting. Thanks.
